### ISSUE TITLE
adobe.com bloqueado

### ISSUE THREAD

**Issue by daniel3xxx** [brunomiguel/antinonio#27]
Bem, isto já começa a ficar um pouco surreal.. Porque é que a lista ficou tão intrusiva agora? Uma lista que o propósito é bloquear o nonio e começa a bloquear tudo...

Mais um exemplo:
https://helpx.adobe.com/lightroom-classic/help/whats-new.html
Ou até mesmo o site principal https://www.adobe.com/

**Comment by krystian3w** [comment]
Because network rules have been rewritten to network filters #24.

In the old formula, you had to manually copy network rules to make the list block harder or catch bugs blocking something unnecessarily.

---

new works filter:
```
||adobe.com^$important
```
old rule no active after simple subscribe - need manually copied to "my rules" panel:
```
 * adobe.com * block
```

**Comment by brunomiguel** [comment]
Como o @krystian3w mencionou, a lista sofreu alterações recentemente e isso fez com que algumas coisas que não estavam a ser bloqueadas passassem a ser bloqueadas. No entanto, já submeti uma alteração para corrigir isso e remover parte do que foi importado desta lista, o projeto original https://nonio.pt/ublock.html

**Comment by brunomiguel** [comment]
@daniel3xxx já de agora, estou sempre à procura de malta que queira testar e/ou submeter regras de bloqueio para os sites da rede nonio. Se estiveres interessado, diz-me alguma coisa, por exemplo, no twitter (https://twitter.com/brunomiguel).
